config/routes.rb
Rails.application.routes.draw do
  resources :songs

  resources :users

  get '/login', to: "sessions#new"

  post '/login', to:  "sessions#create"

  delete '/logout', to: "sessions#destroy"

  root to: "songs#index"
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, :artist, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  has_many :songs

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      flash[:notice] = "You are logged in as #{user.name}"
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:error] = "Invalid login"
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "You have logged out. Feel free to log back in!"
    redirect_to login_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?
  # before_filter is the same thing

  def index
    #@songs = Song.all
    @songs = current_user.songs
  end

  def new
    @song = Song.new
  end

  def show
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to @song
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to @song
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to songs_path
  end

  private

  def song_params
    params.require(:song).permit(:title, :artist)
  end

  def set_song
    #@song = Song.find(params[:id])
    @song = current_user.songs.find(params[:id])
  end

  def logged_in?
    unless current_user
      flash[:notice] = "Please login first"
      redirect_to login_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyJams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <%= link_to "Logout", logout_path, method: :delete %>
<% else %>
  <%= link_to "Login", login_path %>
<% end %>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash-#{name}" %>
    <% end %>

<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :artist %>
  <%= f.text_field :artist %>

  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing...</h1>

<%= render 'form' %>

app/views/songs/index.html.erb
<h1>All Songs</h1>

<ul>
  <% @songs.each do |song| %>
    <li><%= link_to song.title, song_path(song) %></li>
  <% end %>
</ul>

<%= link_to "New Songs", new_song_path %>

app/views/songs/new.html.erb
<h2>Create a new song!</h2>

<%= render 'form' %>

app/views/songs/show.html.erb
<h1>Title: <%= @song.title %></h1>
<h4>Song by: <%= @song.artist %></h4>


<%= link_to "Edit Song", edit_song_path(@song) %>

<%= link_to "Delete Song", song_path(@song), method: :delete %>